/**
 * Builds the party data from data/players.csv and data/events.csv, deals
 * supporters and bonus teams, and writes data/import.sql.
 *
 *   npm run import                 # refuses to run if the database already has events
 *   npm run import -- --force      # replaces all existing party data
 *   npm run import -- --seed=xyz   # different random dealing
 *
 * Apply the generated SQL in the Supabase SQL editor (or ask Claude to apply it).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRng, dealBonus, dealStandard, type Assignment } from "../app/lib/assign";
import { parseCsv } from "./csv";
import { DEFAULT_POINTS, STANDARD_TEAMS, teamsForKind, type EventKind } from "../app/lib/scoring";

const args = process.argv.slice(2);
const force = args.includes("--force");
const seed = args.find((a) => a.startsWith("--seed="))?.slice(7) ?? "party-2026-10-11";

interface EventRow {
  position: number;
  name: string;
  kind: EventKind;
  competitors?: Record<(typeof STANDARD_TEAMS)[number], string>;
}

function fail(errors: string[]): never {
  console.error(`\nFix these problems in the CSV files:\n${errors.map((e) => `  - ${e}`).join("\n")}\n`);
  process.exit(1);
}

const players = parseCsv(readFileSync("data/players.csv", "utf8")).map((r) => r.name);
const eventRows = parseCsv(readFileSync("data/events.csv", "utf8"));

const errors: string[] = [];
const playerSet = new Set(players);
if (players.some((p) => !p)) errors.push("players.csv has a blank name");
if (playerSet.size !== players.length) {
  const dupes = players.filter((p, i) => players.indexOf(p) !== i);
  errors.push(`players.csv has duplicate names: ${[...new Set(dupes)].join(", ")}`);
}

const events: EventRow[] = eventRows.map((row, i) => {
  const line = `events.csv row ${i + 2}`;
  const position = Number(row.position);
  const kind = row.kind as EventKind;
  if (!Number.isInteger(position) || position < 1) errors.push(`${line}: position must be 1, 2, 3...`);
  if (!row.name) errors.push(`${line}: name is blank`);
  if (kind !== "standard" && kind !== "bonus") errors.push(`${line}: kind must be standard or bonus`);
  if (kind !== "standard") return { position, name: row.name, kind };

  const competitors = Object.fromEntries(STANDARD_TEAMS.map((t) => [t, row[t]])) as EventRow["competitors"] & {};
  for (const team of STANDARD_TEAMS) {
    if (!competitors[team]) errors.push(`${line} (${row.name}): no ${team} competitor`);
    else if (!playerSet.has(competitors[team])) {
      errors.push(`${line} (${row.name}): ${team} competitor "${competitors[team]}" isn't in players.csv`);
    }
  }
  if (new Set(Object.values(competitors)).size !== STANDARD_TEAMS.length) {
    errors.push(`${line} (${row.name}): the same person is competing twice`);
  }
  return { position, name: row.name, kind, competitors };
});
const positions = events.map((e) => e.position);
if (new Set(positions).size !== positions.length) errors.push("events.csv has duplicate positions");
if (errors.length) fail(errors);

events.sort((a, b) => a.position - b.position);

const rng = createRng(seed);
const assignments = new Map<number, Assignment[]>(
  events.map((e) => [
    e.position,
    e.competitors ? dealStandard(players, e.competitors, rng) : dealBonus(players, rng),
  ]),
);

// Build SQL that links rows by player name and event position, so no generated IDs are needed.
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const sql = [
  "-- Generated by scripts/import.ts. Do not edit by hand.",
  `-- Seed: ${seed}`,
  "begin;",
  force
    ? "delete from events;\ndelete from players;"
    : `do $$ begin
  if exists (select 1 from events) then
    raise exception 'Party data already exists. Rerun the import with --force to replace it (this changes team assignments).';
  end if;
end $$;`,
  `insert into players (name) values\n${players.map((p) => `  (${q(p)})`).join(",\n")};`,
  `insert into events (position, name, kind, points) values\n${events
    .map((e) => `  (${e.position}, ${q(e.name)}, ${q(e.kind)}, '{${DEFAULT_POINTS[e.kind].join(",")}}')`)
    .join(",\n")};`,
  `insert into event_teams (event_id, team)
select e.id, v.team::team_key
from (values
${events
  .flatMap((e) => teamsForKind(e.kind).map((t) => `  (${e.position}, ${q(t)})`))
  .join(",\n")}
) as v(position, team)
join events e on e.position = v.position;`,
  `insert into event_members (event_id, player_id, team, role)
select e.id, p.id, v.team::team_key, v.role
from (values
${events
  .flatMap((e) =>
    assignments.get(e.position)!.map((a) => `  (${e.position}, ${q(a.player)}, ${q(a.team)}, ${q(a.role)})`),
  )
  .join(",\n")}
) as v(position, player, team, role)
join events e on e.position = v.position
join players p on p.name = v.player;`,
  "commit;",
  "",
].join("\n\n");

writeFileSync("data/import.sql", sql);

// Summary for a quick sanity check
console.log(`\n${players.length} players, ${events.length} events (seed "${seed}")\n`);
for (const e of events) {
  const sizes = teamsForKind(e.kind)
    .map((t) => `${t} ${assignments.get(e.position)!.filter((a) => a.team === t).length}`)
    .join(", ");
  console.log(`  ${String(e.position).padStart(2)}. ${e.name.padEnd(24)} ${sizes}`);
}
const competing = new Map(players.map((p) => [p, 0]));
for (const e of events) for (const p of Object.values(e.competitors ?? {})) competing.set(p, competing.get(p)! + 1);
const byCount = new Map<number, string[]>();
for (const [p, n] of competing) byCount.set(n, [...(byCount.get(n) ?? []), p]);
console.log("\nTimes competing:");
for (const [n, names] of [...byCount].sort((a, b) => a[0] - b[0])) {
  console.log(`  ${n}x: ${names.join(", ")}`);
}
console.log(`\nWrote data/import.sql${force ? " (replaces existing data)" : ""}\n`);
