/**
 * Builds the party data from data/players.csv, data/events.csv, and
 * data/heats.csv, deals supporters, and writes data/import.sql.
 *
 *   npm run import                 # refuses to run if the database already has events
 *   npm run import -- --force      # replaces all existing party data
 *   npm run import -- --seed=xyz   # different random dealing
 *
 * Apply the generated SQL in the Supabase SQL editor (or ask Claude to apply it).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { DEFAULT_POINTS, TEAMS } from "../app/lib/scoring";
import { buildParty } from "./party";

const args = process.argv.slice(2);
const force = args.includes("--force");
const seed = args.find((a) => a.startsWith("--seed="))?.slice(7) ?? "party-2026-10-11";

const read = (file: string) => readFileSync(`data/${file}`, "utf8");
const { party, errors, warnings } = buildParty({
  playersCsv: read("players.csv"),
  eventsCsv: read("events.csv"),
  heatsCsv: read("heats.csv"),
  seed,
});

if (!party) {
  console.error(`\nFix these problems in the CSV files:\n${errors.map((e) => `  - ${e}`).join("\n")}\n`);
  process.exit(1);
}
if (warnings.length) {
  console.warn(`\nWarnings:\n${warnings.map((w) => `  - ${w}`).join("\n")}`);
}

const { players, events, assignments } = party;

// Build SQL that links rows by player name and event position, so no generated IDs are needed.
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const points = `'{${DEFAULT_POINTS.join(",")}}'`;
const heatRows = events.flatMap((e) => e.heats.map((_, i) => ({ position: e.position, heat: i + 1 })));

const sql = [
  "-- Generated by scripts/import.ts. Do not edit by hand.",
  `-- Seed: ${seed}`,
  "begin;",
  force
    ? "delete from events;\ndelete from players;"
    : `do $$ begin
  if exists (select 1 from events) then
    raise exception 'Party data already exists. Rerun the import with --force to replace it (this changes team assignments).';
  end if;
end $$;`,
  `insert into players (name) values\n${players.map((p) => `  (${q(p)})`).join(",\n")};`,
  `insert into events (position, name, description, points) values\n${events
    .map((e) => `  (${e.position}, ${q(e.name)}, ${e.description ? q(e.description) : "null"}, ${points})`)
    .join(",\n")};`,
  `insert into heats (event_id, number)
select e.id, v.heat
from (values
${heatRows.map((h) => `  (${h.position}, ${h.heat})`).join(",\n")}
) as v(position, heat)
join events e on e.position = v.position;`,
  `insert into event_teams (event_id, team)
select e.id, v.team::team_key
from (values
${events.flatMap((e) => TEAMS.map((t) => `  (${e.position}, ${q(t)})`)).join(",\n")}
) as v(position, team)
join events e on e.position = v.position;`,
  `insert into heat_results (event_id, heat, team)
select e.id, v.heat, v.team::team_key
from (values
${heatRows.flatMap((h) => TEAMS.map((t) => `  (${h.position}, ${h.heat}, ${q(t)})`)).join(",\n")}
) as v(position, heat, team)
join events e on e.position = v.position;`,
  `insert into event_members (event_id, player_id, team, role, heat)
select e.id, p.id, v.team::team_key, v.role, v.heat::int
from (values
${events
  .flatMap((e) =>
    assignments
      .get(e.position)!
      .map((a) => `  (${e.position}, ${q(a.player)}, ${q(a.team)}, ${q(a.role)}, ${a.heat ?? "null"})`),
  )
  .join(",\n")}
) as v(position, player, team, role, heat)
join events e on e.position = v.position
join players p on p.name = v.player;`,
  "commit;",
  "",
].join("\n\n");

writeFileSync("data/import.sql", sql);

// Summary for a quick sanity check
console.log(`\n${players.length} players, ${events.length} games (seed "${seed}")\n`);
for (const e of events) {
  const dealt = assignments.get(e.position)!;
  const sizes = TEAMS.map((t) => `${t} ${dealt.filter((a) => a.team === t).length}`).join(", ");
  const heats = e.heats.length === 1 ? "1 heat " : `${e.heats.length} heats`;
  const perTeam = Math.max(...e.heats.flatMap((h) => TEAMS.map((t) => h[t].length)));
  console.log(
    `  ${String(e.position).padStart(2)}. ${e.name.padEnd(22)} ${heats}  ${perTeam}/team  teams: ${sizes}`,
  );
}
const competing = new Map(players.map((p) => [p, 0]));
for (const dealt of assignments.values()) {
  for (const a of dealt) if (a.role === "competitor") competing.set(a.player, competing.get(a.player)! + 1);
}
const byCount = new Map<number, string[]>();
for (const [p, n] of competing) byCount.set(n, [...(byCount.get(n) ?? []), p]);
console.log("\nGames competed in:");
for (const [n, names] of [...byCount].sort((a, b) => a[0] - b[0])) {
  console.log(`  ${n}x: ${names.join(", ")}`);
}
console.log(`\nWrote data/import.sql${force ? " (replaces existing data)" : ""}\n`);
